name: Create and Execute Iris Pipeline

on:
  push:
    branches:
      - main

jobs:
  pipeline_job:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      PIPELINE_NAME: 'IrisMLOpsPipeline'
      ROLE_ARN: arn:aws:iam::866824485776:role/service-role/AmazonSageMaker-ExecutionRole-20240913T125305  # Replace with your SageMaker IAM role ARN
      BUCKET_NAME: 'sagemaker-us-east-1-866824485776'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create SageMaker Pipeline
        env:
          ROLE_ARN: ${{ env.ROLE_ARN }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
        run: |
          python create_sagemaker_pipeline.py

      - name: Execute SageMaker Pipeline
        env:
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
        run: |
          aws sagemaker start-pipeline-execution --pipeline-name ${{ env.PIPELINE_NAME }}
